#!/bin/bash
service postgresql start
service metasploit start
service mysql start
/etc/init.d/apache2 start
service tor start
echo "
Services Started 
======================
-PostgreSQL
-Metasploit
-Apache
-Mysql
-Tor
"
